### ISSUE TITLE
ImportError: cannot import name 'Animate' from render.render

### ISSUE THREAD

**Issue by codymtaylor** [inconvergent/differential-line#2]
I enjoy your generative artwork and have downloaded your code for differential line to try to play around with myself.  I'm having a hard time getting it to run. Currently on a fresh install of python 3.5 (anaconda-installed Jupyter) in Ubuntu.  I installed your other packages zonemap and render and then installed differential-line. This appeared to work.  Then when I try to run main_ani.py in differential-line, I get the this error:

```
ydoc@ydoc-VirtualBox:~/Downloads/differential-line-master$ python3 main_ani.py
Traceback (most recent call last):
  File "main_ani.py", line 131, in <module>
    main()
  File "main_ani.py", line 69, in main
    from render.render import Animate
  File "/home/ydoc/.local/lib/python3.5/site-packages/render-0.0.4-py3.5.egg/render/__init__.py", line 3, in <module>
ImportError: cannot import name 'Animate'
```

I think this ImportError is usually caused by either circular references (doesn't seem to be an issue here) or perhaps something to do with python 2.x code being run under python 3.5.  Do you have any idea what's causing this?

Thanks for any insight you can share.

**Comment by inconvergent** [comment]
differential line and render (https://github.com/inconvergent/render) is only tested under python 2. you will have to work out the dependencies on your own if you want to run it under python 3. 

I'm in the process of porting my work to python 3, but I have not finished all repos, and I probably wont for quite a while.
