### ISSUE TITLE
ImportError: cannot import name Fn

### ISSUE THREAD

**Issue by codymtaylor** [inconvergent/differential-line#3]
Hi Anders,
Trying the code now in Py 2.7 - thanks for your note about compatibility.  re-installed zonemap and render and differential-line there.  Now running main_ani.py from differential-line and get the following:

```
(py27) ydoc@ydoc-VirtualBox:~/Downloads/differential-line-master$ python main_ani.py
nmax: 1000000
number of zones: 35
zonewidth: 0.028571
nearl: 0.001071
farl: 0.014286
Traceback (most recent call last):
  File "main_ani.py", line 131, in <module>
    main()
  File "main_ani.py", line 83, in main
    from fn import Fn
ImportError: cannot import name Fn
```
I don't see a module named Fn - is this an external dependency?  I thought it might be [https://pypi.python.org/pypi?:action=display&name=fn](https://pypi.python.org/pypi?:action=display&name=fn) but I'm not sure.  

Thanks!

**Comment by inconvergent** [comment]
it's this: https://github.com/inconvergent/fn

i've added it to the requirements list.
