### ISSUE TITLE
import DifferentialLine

### ISSUE THREAD

**Issue by gguiomar** [inconvergent/differential-line#4]
Hey! 

I'm trying to run your code and I'm getting an 'ImportError: No module named differentialLine' in the main_line_ani.py file.

I noted there is a class named DifferentialLine in the src/differentialLine.pyx, but I'm not sure on what needs to be done to import this class to the main file.

Cheers,
gg

**Comment by a-dpq** [comment]
I'm also running into this error. How can we solve this?

**Comment by gtcdevop** [comment]
Same issue here
![screen shot 2018-09-21 at 01 47 36](https://user-images.githubusercontent.com/28716084/45860950-5667cd00-bd40-11e8-800c-b2cad966f486.png)

**Comment by gtcdevop** [comment]
I've found a solution: 
1- Compile and install numpy correct version
2- Ran python3 setup.py install on PROJECT FOLDER  -- to install DifferentialLine
3- Compiled and. installl the following libraries 
```
https://github.com/inconvergent/fn
https://github.com/inconvergent/iutils.git
https://github.com/inconvergent/zonemap
```

Loot and lets see how nature works

![screen shot 2018-09-21 at 02 14 23](https://user-images.githubusercontent.com/28716084/45861632-14408a80-bd44-11e8-8548-779b0765a29d.png)
